---
abstract: 链接DBIx::Custom到Mojolicious的插件
author:
  - 'wfso <461663376@qq.com>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.3, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-DBIxCustom
no_index:
  directory:
    - t
    - inc
requires:
  DBIx::Custom: '0.40'
  Mojolicious: '7.48'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/wfso/Mojolicious-Plugin-DBIxCustom/issues
  homepage: https://github.com/wfso/Mojolicious-Plugin-DBIxCustom/wiki
  license: https://opensource.org/licenses/MIT
  repository: https://github.com/wfso/Mojolicious-Plugin-DBIxCustom.git
version: v0.1.0
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
